# Generated by Django 3.2 on 2024-08-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('comm', '0002_notification_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Comm',
        ),
    ]
