# Generated by Django 5.1 on 2024-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number_user_preferred_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ref_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('AR', 'Arabic')], max_length=2, null=True),
        ),
    ]
